# Generated by Django 5.1.1 on 2024-10-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('uname', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('passw', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
