# Generated by Django 5.1.1 on 2024-11-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('cname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=52)),
                ('crs', models.CharField(max_length=20)),
                ('em', models.CharField(max_length=40)),
                ('cno', models.CharField(max_length=12)),
                ('addr', models.CharField(max_length=80)),
                ('loc', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'collage',
            },
        ),
    ]
