# Generated by Django 5.1.1 on 2024-11-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_collage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('cid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=52)),
                ('cno', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('qry', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'enquiry',
            },
        ),
    ]
