# Generated by Django 5.1.1 on 2024-12-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=52)),
                ('phone', models.CharField(max_length=12)),
                ('query', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'callme',
            },
        ),
    ]
