# Generated by Django 5.1.1 on 2024-12-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_callme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forgotps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newpass', models.CharField(max_length=30)),
                ('conformpass', models.CharField(max_length=52)),
            ],
            options={
                'db_table': 'forgot',
            },
        ),
    ]
